default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_development
  host: localhost
  username: postgres
  password: changeme
  port: 5432

test:
  <<: *default
  database: api_test
  host: localhost
  username: postgres
  password: changeme
  port: 5432
